application: family-iem
version: 1
runtime: python27
api_version: 1
threadsafe: true
  
handlers:
- url: /content
  static_dir: content

- url: /account/.*
  script: account.membership.app
      
- url: /help/.*
  script: shared.help.app
  
- url: /error/.*
  script: shared.help.app
  
- url: /.*
  script: home.index.app

libraries:
- name: jinja2
  version: latest