application: family-iem
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /account/.*
  script: apps.account.app

- url: /help/.*
  script: apps.shared.app

- url: /error/.*
  script: apps.shared.app

- url: /.*
  script: apps.home.app

libraries:
- name: jinja2
  version: latest